# Generated by Django 5.1.13 on 2025-10-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0016_v0_9_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHHostkeyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name',), name='sshhostkeyfile_name_unique')],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='ssh_hostkey_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_fk_sshhostkeyfile', to='aw.sshhostkeyfile'),
        ),
        migrations.AddField(
            model_name='repository',
            name='ssh_hostkey_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repo_fk_sshhostkeyfile', to='aw.sshhostkeyfile'),
        ),
        migrations.CreateModel(
            name='SSHHostkeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=300)),
                ('_hostkeys', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sshhostkey_fk_file', to='aw.sshhostkeyfile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('host',), name='sshhostkey_host_unique')],
            },
        ),
    ]
