# Generated by Django 5.1.8 on 2026-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0017_v0_9_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='ansible_executor',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ansible-runner (official)'), (1, 'oxl-ansible-executor (community)')], default=0),
        ),
    ]
