# Generated by Django 5.1.8 on 2026-05-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0018_v0_9_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='_extra_vars',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='_extra_vars',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ansible_executor_container_image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ansible_executor_engine',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Local'), (1, 'Docker container'), (2, 'Podman container')], default=0),
        ),
    ]
