# Generated by Django 5.1.15 on 2026-05-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0018_v0_9_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='_extra_vars',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='_extra_vars',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
