# Generated by Django 5.2.17 on 2026-09-17 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("aw", "0019_v0_9_5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="session_expire_at_browser_close",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userextended",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("de", "Deutsch"), ("es", "Español")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="alertglobal",
            name="jobs",
            field=models.ManyToManyField(
                through="aw.AlertGlobalJobMapping",
                through_fields=("alert", "job"),
                to="aw.job",
            ),
        ),
        migrations.AlterField(
            model_name="alertgroup",
            name="jobs",
            field=models.ManyToManyField(
                through="aw.AlertGroupJobMapping",
                through_fields=("alert", "job"),
                to="aw.job",
            ),
        ),
        migrations.AlterField(
            model_name="alertuser",
            name="jobs",
            field=models.ManyToManyField(
                through="aw.AlertUserJobMapping",
                through_fields=("alert", "job"),
                to="aw.job",
            ),
        ),
        migrations.AlterField(
            model_name="jobpermission",
            name="credentials",
            field=models.ManyToManyField(
                through="aw.JobCredentialsPermissionMapping",
                through_fields=("permission", "credentials"),
                to="aw.jobsharedcredentials",
            ),
        ),
        migrations.AlterField(
            model_name="jobpermission",
            name="groups",
            field=models.ManyToManyField(
                through="aw.JobPermissionMemberGroup",
                through_fields=("permission", "group"),
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="jobpermission",
            name="jobs",
            field=models.ManyToManyField(
                through="aw.JobPermissionMapping",
                through_fields=("permission", "job"),
                to="aw.job",
            ),
        ),
        migrations.AlterField(
            model_name="jobpermission",
            name="repositories",
            field=models.ManyToManyField(
                through="aw.JobRepositoryPermissionMapping",
                through_fields=("permission", "repository"),
                to="aw.repository",
            ),
        ),
        migrations.AlterField(
            model_name="jobpermission",
            name="users",
            field=models.ManyToManyField(
                through="aw.JobPermissionMemberUser",
                through_fields=("permission", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
