# Generated by Django 5.1.8 on 2026-06-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0019_v0_9_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='session_expire_at_browser_close',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userextended',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('es', 'Español')], default='en', max_length=10),
        ),
    ]
