FROM python:3.12-alpine

# BUILD: docker build -f Dockerfile_dev -t oxlorg/ansible-webui:dev --no-cache .
# RUN: docker run -it --name ansible-webui-dev --volume /tmp/awtest:/data --volume $(pwd):/aw ansible-webui:dev

RUN apk add --update --no-cache openssh-client sshpass xmlsec && \
    pip install --no-cache-dir --upgrade pip 2>/dev/null && \
    mkdir -p /data/log

ENV AW_ENV=dev \
    AW_VERSION=dev \
    AW_DOCKER=1 \
    PYTHONUNBUFFERED=1 \
    AW_DB=/data/aw.db \
    AW_PATH_LOG=/data/log \
    AW_PATH_PLAY=/aw/test
WORKDIR /aw/test
EXPOSE 8000

COPY --chmod=0755 entrypoint_dev.sh /entrypoint.sh
COPY --chmod=0755 requirements.sh /entrypoint_requirements.sh
ENTRYPOINT ["/entrypoint.sh"]
