ARG AW_VERSION=0.0

# BUILD CMD: docker build -f Dockerfile_production -t ansible-webui:<VERSION> --build-arg "AW_VERSION=<VERSION>" --no-cache .
# RUN: docker run -d --name ansible-webui --publish 127.0.0.1:8000:8000 --volume $(pwd)/ansible/data:/data --volume $(pwd)/ansible/play:/play ansible-webui:<VERSION>


FROM node:23-alpine AS builder

ARG AW_VERSION
WORKDIR /tmp

RUN echo $AW_VERSION

RUN apk add --no-cache curl zip bash && \
    curl -sLO https://github.com/O-X-L/ansible-webui/archive/refs/heads/${AW_VERSION}.zip && \
    unzip /tmp/${AW_VERSION}.zip >/dev/null && \
    cd /tmp/ansible-webui-${AW_VERSION}/frontend && \
    npm install

RUN bash /tmp/ansible-webui-${AW_VERSION}/scripts/frontend/build_base.sh /tmp/ansible-webui-${AW_VERSION}/frontend/src /tmp/ansible-webui-${AW_VERSION}/src/oxl_ansible_webui/aw/static_dev
RUN ls -l /tmp/ansible-webui-${AW_VERSION}/src/oxl_ansible_webui/aw/static_dev/

