ARG AW_VERSION

FROM python:3.12-slim AS builder_mysql

RUN apt-get update && \
    apt-get -y --no-install-recommends install git python3-dev default-libmysqlclient-dev build-essential pkg-config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mysqlclient

FROM oxlorg/ansible-webui-unprivileged:${AW_VERSION}-debian
ARG AW_USER=aw
ARG PY_VERSION=3.12

USER root

RUN apt-get update && \
    apt-get -y --no-install-recommends install libmariadb3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder_mysql /usr/local/lib/python${PY_VERSION}/site-packages/MySQLdb /usr/local/lib/python${PY_VERSION}/site-packages/MySQLdb
COPY --from=builder_mysql /usr/local/lib/python${PY_VERSION}/site-packages/mysqlclient-*.dist-info /usr/local/lib/python${PY_VERSION}/site-packages/

USER ${AW_USER}
