ARG AW_VERSION=0.0

FROM python:3.12-slim AS aw
ARG AW_VERSION

RUN apt-get update && \
    apt-get -y --no-install-recommends install git git-lfs openssh-client sshpass xmlsec1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /data/log

ENV AW_VERSION=${AW_VERSION}.dev \
    AW_DEV=1 \
    AW_ENV='dev' \
    AW_DOCKER=1 \
    AW_SECRET='asdfThisIsSuperSecret!12345678' \
    AW_DB=/repo/src/oxl_ansible_webui/aw.dev.db \
    AW_PATH_PLAY=/repo/test \
    AW_PATH_LOG=/data/log \
    DJANGO_SUPERUSER_USERNAME='ansible' \
    DJANGO_SUPERUSER_PASSWORD='automateMe' \
    DJANGO_SUPERUSER_EMAIL='ansible@localhost' \
    DEV_CLEAN=0 \
    DEV_INIT=1 \
    PYTHONUNBUFFERED=1
WORKDIR /repo/test
EXPOSE 8000

COPY --chmod=0755 entrypoint_dev_backend.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
