ARG AW_VERSION

# BUILD: docker build -f Dockerfile_production_unprivileged -t ansible-webui:<VERSION> --build-arg "AW_VERSION=<VERSION>" --progress=plain --no-cache .
# RUN:
#   sudo useradd ansible-webui --shell /usr/sbin/nologin --uid 8785 --user-group
#   mkdir ${YOUR_DATA_DIR} && chown -R ansible-webui ${YOUR_DATA_DIR}
#   docker run -d --name ansible-webui --publish 127.0.0.1:8000:8000 --volume ${YOUR_DATA_DIR}:/data --volume $(pwd)/ansible/play:/play ansible-webui:<VERSION>

FROM oxlorg/ansible-webui-builder-fe:${AW_VERSION} AS builder

FROM oxlorg/ansible-webui:${AW_VERSION}-alpine

ARG AW_VERSION
ARG AW_UID=8785
ARG AW_USER=aw

RUN adduser --uid ${AW_UID} --home /home/ansible-webui --shell /usr/sbin/nologin --disabled-password ${AW_USER} ${AW_USER} && \
    chown -R ${AW_USER}:${AW_USER} /data /play

USER ${AW_USER}
