ARG AW_VERSION=0.0

# BUILD: docker build -f Dockerfile_production_unprivileged -t ansible-webui:<VERSION> --build-arg "AW_VERSION=<VERSION>" --progress=plain --no-cache .
# RUN:
#   sudo useradd ansible-webui --shell /usr/sbin/nologin --uid 8785 --user-group
#   mkdir ${YOUR_DATA_DIR} && chown -R ansible-webui ${YOUR_DATA_DIR}
#   docker run -d --name ansible-webui --publish 127.0.0.1:8000:8000 --volume ${YOUR_DATA_DIR}:/data --volume $(pwd)/ansible/play:/play ansible-webui:<VERSION>

FROM node:23-alpine AS builder

ARG AW_VERSION
WORKDIR /tmp

RUN echo $AW_VERSION

# NOTE: need to change .../archive/refs/tags/... to .../refs/heads/... if branch is the target
RUN apk add --no-cache curl zip bash && \
    curl -sLO https://github.com/O-X-L/ansible-webui/archive/refs/tags/${AW_VERSION}.zip && \
    unzip /tmp/${AW_VERSION}.zip >/dev/null && \
    cd /tmp/ansible-webui-${AW_VERSION}/frontend && \
    npm install

RUN bash /tmp/ansible-webui-${AW_VERSION}/scripts/frontend/build_base.sh /tmp/ansible-webui-${AW_VERSION}/frontend/ /tmp/ansible-webui-${AW_VERSION}/src/oxl_ansible_webui/aw/static_prod/dist/ && \
    ls /tmp/ansible-webui-${AW_VERSION}/src/oxl_ansible_webui/aw/static_prod/dist/ && \
    bash /tmp/ansible-webui-${AW_VERSION}/scripts/frontend/validate_prod_build.sh

FROM python:3.11-alpine AS aw

ARG AW_VERSION
ARG AW_UID=8785
ARG AW_USER=aw

RUN apk add --no-cache git git-lfs openssh-client sshpass xmlsec && \
    pip install --no-cache-dir --upgrade pip 2>/dev/null && \
    pip install --no-cache-dir "git+https://github.com/O-X-L/ansible-webui.git@${AW_VERSION}" && \
    adduser --uid ${AW_UID} --home /home/ansible-webui --shell /usr/sbin/nologin --disabled-password ${AW_USER} ${AW_USER} && \
    mkdir -p /play /data/log && \
    chown -R ${AW_USER}:${AW_USER} /data /play

COPY --from=builder /tmp/ansible-webui-${AW_VERSION}/src/oxl_ansible_webui/aw/static_prod/ /usr/local/lib/python3.11/site-packages/oxl_ansible_webui/aw/static_prod/

ENV AW_VERSION=${AW_VERSION} \
    AW_DOCKER=1 \
    PYTHONUNBUFFERED=1 \
    AW_DB=/data/aw.db \
    AW_PATH_LOG=/data/log \
    AW_PATH_PLAY=/play
WORKDIR /play
USER ${AW_USER}
EXPOSE 8000

COPY --chmod=0755 entrypoint_production.sh /entrypoint.sh
COPY --chmod=0755 requirements.sh /entrypoint_requirements.sh
ENTRYPOINT ["/entrypoint.sh"]
