ARG AW_VERSION=0.0

FROM oxlorg/ansible-webui-unprivileged:${AW_VERSION}-debian
ARG AW_USER=aw

USER root
RUN apt-get update && \
    apt-get -y --no-install-recommends install default-libmysqlclient-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir "oxl-ansible-webui[mysql] @ git+https://github.com/O-X-L/ansible-webui.git@${AW_VERSION}"

USER ${AW_USER}
