ARG AW_VERSION=0.0

# BUILD: docker build -f Dockerfile_production -t ansible-webui:<VERSION> --build-arg "AW_VERSION=<VERSION>" --progress=plain --no-cache .
# RUN: docker run -d --name ansible-webui --publish 127.0.0.1:8000:8000 --volume $(pwd)/ansible/data:/data --volume $(pwd)/ansible/play:/play ansible-webui:<VERSION>

FROM oxlorg/ansible-webui-builder-fe:${AW_VERSION} AS builder

FROM python:3.12-alpine AS aw
ARG AW_VERSION
ARG PY_VERSION=3.12

RUN apk add --update --no-cache git git-lfs openssh-client sshpass xmlsec && \
    pip install --no-cache-dir --upgrade pip 2>/dev/null && \
    pip install --no-cache-dir "git+https://github.com/O-X-L/ansible-webui.git@${AW_VERSION}" && \
    mkdir -p /play /data/log

COPY --from=builder /tmp/ansible-webui-${AW_VERSION}/src/oxl_ansible_webui/aw/static_prod/ /usr/local/lib/python${PY_VERSION}/site-packages/oxl_ansible_webui/aw/static_prod/

ENV AW_VERSION=${AW_VERSION} \
    AW_DOCKER=1 \
    PYTHONUNBUFFERED=1 \
    AW_DB=/data/aw.db \
    AW_PATH_LOG=/data/log \
    AW_PATH_PLAY=/play
WORKDIR /play
EXPOSE 8000

COPY --chmod=0755 entrypoint_production.sh /entrypoint.sh
COPY --chmod=0755 requirements.sh /entrypoint_requirements.sh
ENTRYPOINT ["/entrypoint.sh"]
