---

name: Test Frontend

on:
  push:
    branches: [latest]
    paths:
      - '**.js'
      - '**.ts'
      - '**.svelte'
      - 'frontend/*.json'
      - 'frontend/*.config.js'
      - 'frontend/*.config.ts'
      - '.github/workflows/test_frontend.yml'
  pull_request:
    branches: [latest]
    paths:
      - '**.js'
      - '**.ts'
      - '**.svelte'
      - 'frontend/*.json'
      - 'frontend/*.config.js'
      - 'frontend/*.config.ts'
      - '.github/workflows/test_frontend.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Install backend dependencies
        run: |
          pip install -r requirements.txt >/dev/null
          pip install -r requirements_test_frontend.txt >/dev/null

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend/

      - name: Building frontend
        run: bash scripts/frontend/build.sh
        env:
          FORCE_UPDATE: 1

      - name: Running Integration Tests
        run: |
          export AW_ENV='dev'
          export AW_DB="/tmp/$(date +%s).aw.db"
          export AW_ADMIN='tester'
          export AW_ADMIN_PWD='someSecret!Pwd'
          rm -rf src/oxl_ansible_webui/aw/migrations/*
          python3 src/oxl_ansible_webui/ >/dev/null 2>/dev/null &
          sleep 5

          echo 'WEB-UI INTEGRATION TESTS'
          python3 test/integration/webui/main.py
          sleep 1

          pkill -f oxl_ansible_webui

      - name: Running Integration Tests - AUTH SAML
        run: |
          sleep 5
          export AW_ENV='dev'
          export AW_DB="/tmp/$(date +%s).aw.db"
          export AW_ADMIN='tester'
          export AW_ADMIN_PWD='someSecret!Pwd'
          export AW_CONFIG="$(pwd)/test/integration/auth/saml.yml"
          rm -rf src/oxl_ansible_webui/aw/migrations/*
          python3 src/oxl_ansible_webui/ >/dev/null 2>/dev/null &
          sleep 5

          echo 'WEB-UI AUTH-SAML INTEGRATION TESTS'
          python3 test/integration/auth/saml.py
          sleep 1

          pkill -f oxl_ansible_webui
