---

name: Test Databases

on:
  workflow_dispatch:
  push:
    branches: [latest]
    paths:
      - 'src/oxl_ansible_webui/db.py'
      - '.github/workflows/test_dbs.yml'

  pull_request:
    branches: [latest]
    paths:
      - 'src/oxl_ansible_webui/db.py'
      - '.github/workflows/test_dbs.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    services:
      test_mariadb:
        image: 'mariadb:latest'
        options: >
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
        ports:
          - '3306:3306'
        env:
          MARIADB_ROOT_PASSWORD: 'test'
          MARIADB_DATABASE: 'aw'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          pip install -r requirements.txt >/dev/null
          pip install -r requirements_test_backend.txt >/dev/null
          sudo apt install default-libmysqlclient-dev >/dev/null
          pip install mysqlclient >/dev/null

      - name: Testing MariaDB/MySQL
        run: |
          sc=0
          while ! host $AW_DB_HOST >/dev/null 2>/dev/null
          do
            if (( sc > 30 ))
            then
              exit 1
            fi
            sleep 1  # wait for db to start
            ((sc++))
            echo $sc
          done

          bash scripts/test_db_mariadb.sh
        env:
          AW_DB_HOST: 'test_mariadb'
